name: 'Get the tests repo'
description: |
  Checkout the hemelb-tests repo.
  Make sure to set GITHUB_TOKEN in environment!

inputs:
  path:
    description: 'Relative path under $GITHUB_WORKSPACE to place the repository'
    required: true

runs:
  using: 'composite'
  steps:
    - id: ref_name
      shell: bash
      run: |
        if [ $GITHUB_EVENT_NAME = "pull_request" ]; then
          branch=$GITHUB_HEAD_REF
        else
          branch=$GITHUB_REF_NAME
        fi
        echo "value=$branch" >> $GITHUB_OUTPUT

    - uses: octokit/request-action@v2.x
      id: check_branch_exists
      continue-on-error: true
      with:
        route: GET /repos/{org}/{repo}/branches/{branch}
        org: hemelb-codes
        repo: hemelb-tests
        branch: ${{ steps.ref_name.outputs.value }}

    - id: branch
      shell: bash
      run: |
        if [ ${{ steps.check_branch_exists.outputs.status }} = 200 ]; then
          ans=${{ steps.ref_name.outputs.value }}
        else
          ans=main
        fi
        echo "value=$ans" >> "$GITHUB_OUTPUT"

    - uses: actions/checkout@v3
      with:
        repository: hemelb-codes/hemelb-tests
        ref: ${{ steps.branch.outputs.value }}
        path: ${{ inputs.path }}        
