default: 
  CMAKE_BUILD_TYPE: "Release"
  CMAKE_CXX_FLAGS_RELEASE: "-O4"
no_steering:
  HEMELB_STEERING_LIB: "none"
basic_steering:
  HEMELB_STEERING_LIB: "basic"
debug:
  CMAKE_BUILD_TYPE: "Debug"
  HEMELB_LOG_LEVEL: "debug"
  HEMELB_OPTIMISATION: ""
gdb:
  HEMELB_USE_DEBUGGER: "ON"
no_streaklines:
  HEMELB_USE_STREAKLINES: "OFF"
wait_on_connect:
  HEMELB_WAIT_ON_CONNECT: "ON"
