default: 
  # General default values for all machines live in the default dictionary.
  # Machine-specific overrides replace these.
  # Mercurial server to find HemeLB
  hg: "ssh://hg@entropy.chem.ucl.ac.uk"
  # Repository on the mercurial server to find HemeLB
  repository: "hemelb"
  # Default Modules to load or unload on remote, via module 'foo'
  # e.g. ['load cmake'].
  modules: []
  # Commands to execute before attempting a remote build.
  build_prefix_commands: []
  # Commands to execute as part of remote run jobs.
  run_prefix_commands: []
  # Templates to use to find space to checkout and build HemeLB on the remote.
  # All user- and generally- defined values in these config dictionaries will be interpolated via $foo
  home_path_template: "/home/$username"
  # Name for the Project Fabric folder
  fabric_dir: "FabricHemeLb"
  # Path to runtime accessible filesystem (default is same as build time)
  runtime_path_template: "$home_path"
  make_jobs: 1
  corespernode: 1
  # Default options used in the CMake configure step.
  # Command to use to launch remote jobs
  # e.g. qsub, empty string to launch interactively.
  job_dispatch: ''
  # Path to build filesystem folder
  # All user-defined values in these config dictionaries will be interpolated via $foo
  remote_path_template: "$home_path/$fabric_dir"
  # Path to run filesystem folder
  work_path_template: "$runtime_path/$fabric_dir"
  install_path_template: "$remote_path/install"
  # Normally, the regression test can be run directly out of diffTest, but sometimes needs to be copied to a runtime file area.
  regression_test_path_template: "$regression_test_source_path"
  python_build: "TODO"
  template_key: false
  temp_path_template: "/tmp"
  cmake_options: {}
  job_name_template: '${config}_${build_number}_${machine_name}_$cores'
  config_name_template: "${profile}_${StringVoxelSize}_${Steps}_${Cycles}"
legion: 
  job_dispatch: "qsub"
  # The remote host-name to use.
  remote: "legion.rc.ucl.ac.uk"
  # The path python disttools use for builds.
  python_build: "python2.6"
  modules: ["remove ofed/qlogic/intel/64/1.2.7", "add ofed/openmpi/gcc/64/1.4.1", "load cmake", "load python/gcc/2.6.6"]
  runtime_path_template: "$home_path/Scratch"
  node_type_restriction_template: '#$$ -ac allow="${node_type}"'
  node_type: "X"
  corespernode: 12
  temp_path_template: false #Legion sets its own tmpdir
  template_key: legion
legion_intel:
  fabric_dir: "IntelHemeLB"
  import: legion
  modules: ["remove ofed/qlogic/intel/64/1.2.7","add ofed/openmpi/intel/64/1.4.1","load cmake", "load python/gcc/2.6.6"]
  build_prefix_commands: ["export CXX=icpc","export CC=icc", "export LD=icc"] #Tell autoconf for dependencies where the hector compilers are
  cmake_options: 
    HEMELB_USE_ALL_WARNINGS_GNU: "OFF"
    CMAKE_CXX_COMPILER: "icpc"
    CMAKE_C_COMPILER: "icc"
    CMAKE_CXX_FLAGS_RELEASE: ""
    HEMELB_OPTIMISATION: "-O3"
    HEMELB_DEPENDENCIES_SET_RPATH: "OFF"
planck:
  needs_tarballs: true
  remote: "planck.chem.ucl.ac.uk"
  python_build: "lib/python2.6"
  template_key: default
entropy: 
  remote: "entropy.chem.ucl.ac.uk"
  python_build: "lib/python2.6"
  runtime_path_template: "/store4/blood/$username"
  template_key: default
hector:
  max_job_name_chars: 15
  make_jobs: 4
  job_dispatch: "qsub"
  no_ssh: true # Hector doesn't allow outgoing ssh sessions.
  remote: "login.hector.ac.uk"
  # On hector, *all files* which are needed at runtime, must be on the /work filesystem, so we must make the install location be on the /work filesystem
  install_path_template: "$work_path/install"
  home_path_template: "/home/$project/$project/$username"
  runtime_path_template: "/work/$project/$project/$username"
  modules: ["load CMake/2.8.6"]
  build_prefix_commands: ["export CXX=CC","export CC=cc", "export LD=CC"] #Tell autoconf for dependencies where the hector compilers are
  temp_path_template: "$work_path/tmp"
  regression_test_path_template: "$work_path/regression"
  queue: "parallel"
  python_build: "lib64/python2.6"
  corespernode: 32
  cmake_options: 
    HEMELB_USE_ALL_WARNINGS_GNU: "OFF"
    CMAKE_CXX_COMPILER: "CC"
    CMAKE_C_COMPILER: "cc"
    CMAKE_CXX_FLAGS_RELEASE: ""
    HEMELB_OPTIMISATION: "-O3"
    HEMELB_DEPENDENCIES_SET_RPATH: "OFF"
hector_login: #Hector, compiling for login nodes and serial queues
   import: "hector"
   fabric_dir: "FabricHemeLbLogin"
   modules: ["load CMake/2.8.6", "swap xtpe-interlagos xtpe-istanbul"]
   job_dispatch: ""
julian:
   home_path_template: "/Users/$username"
   remote: "julian.chem.ucl.ac.uk"
   python_build: "lib/python2.7"
   template_key: default
oppenheimer:
   remote: "oppenheimer.chem.ucl.ac.uk"
   build_prefix_commands: ["export set PATH=$PATH:/home/jamespjh/install/bin","export set PYTHONPATH=$PYTHONPATH:/home/jamespjh/install/lib/python2.6/site-packages"]
   no_hg: true
   job_dispatch: "qsub"
   python_build: "lib/python2.6"
   make_jobs: 4
localhost:
   remote: "localhost"
   python_build: "lib/python2.7"
   template_key: default
   make_jobs: 4
   