default:
  steering_id: 1111
  port: 65250
steered_parameters:
  - SceneCentreX #0
  - SceneCentreY #1
  - SceneCentreZ #2
  - Longitude #3
  - Latitude #4
  - Zoom #5
  - Brightness #6
  - PhysicalVelocityThresholdMax #7
  - PhysicalStressThresholdMaximum #8
  - PhysicalPressureThresholdMinimum #9
  - PhysicalPressureThresholdMaximum #10
  - GlyphLength #11
  - PixelsX #12
  - PixelsY #13
  - NewMouseX #14
  - NewMouseY #15
  - SetIsTerminal #16
  - Mode #17
  - StreaklinePerSimulation #18
  - StreallineLength #19
  - SetDoRendering #20
localhost:
  remote: "localhost"