name: Python tools

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/py-*'
      - 'python-tools/**'

  pull_request:

  schedule:
    # Run every Monday 0700 UTC
    - cron: '0 7 * * 1'

jobs:
  python-lint:
    runs-on: ubuntu-22.04

    defaults:
      run:
        working-directory: python-tools

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: install
        run: |
          pip install black~=22.0

      - name: Run black format check
        run: black --check .

  python-tests:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        python-version:
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'

    env:
      HEMELB_TESTS_DIR: ${{ github.workspace }}/tests

    steps:
      - uses: actions/checkout@v3
        with:
          path: main

      - name: Get hemelb-tests repo
        uses: ./main/.github/actions/get-tests-repo
        with:
          path: tests
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: install tox
        run: |
          pip install -U pip setuptools wheel
          pip install tox tox-gh-actions


      - name: Test with tox
        run: tox
        working-directory: main/python-tools
