results:
    xml_files:
        'results/report.xml':
            total: 'timings/timer[name="Total"]/mean'
        'config.xml':
            steps: ['simulation','cyclesteps']
    text_files:
        'results/report.txt':
            cores: 'Ran with ([\d]+) threads'
        'CMakeCache.txt':
            build_type: 'CMAKE_BUILD_TYPE:STRING=(.*)'
    name_properties:
        machine: '_([^_]*)_\d$'

graphs:
    performance_versus_core:
        name: "Performance on ${machine} versus core count"
        select:
            type: hemelb
        curves:
            - cores
        dependent:
            - total
        independent:
            - steps
            
reports:
    performance_on_planck:
        name: Performance on planck
        graphs:
            performance_versus_core:
        defaults:
            select:
                machine: planck
