# 
# Copyright (C) University College London, 2007-2012, all rights reserved.
# 
# This file is part of HemeLB and is CONFIDENTIAL. You may not work 
# with, install, use, duplicate, modify, redistribute or share this
# file, or any part thereof, other than as allowed by any agreement
# specifically made by you with University College London.
# 
# Copy this file as config.yml, and specify your configuration details
results_path: "~/devel/ccs/fabric/hemelb/results"
reports_path: "~/devel/ccs/fabric/hemelb/reports"