results:
    xml_files:
        'results/report.xml':
            total: 'timings/timer[name="Total"]/mean'
            sites: 'geometry/sites'
        'config.xml':
            steps: ['simulation','cyclesteps']
    text_files:
        'results/report.txt':
            cores: 'Ran with ([\d]+) threads'
        'CMakeCache.txt':
            build_type: 'CMAKE_BUILD_TYPE:STRING=(.*)'
    name_properties:
        machine_by_name: '_([^_]*)_\d$'
    yaml_files:
        'env.yml':
            type: script
            machine: machine_name
            build_number: build_number

graphs:
    performance_versus_size:
        name: "Performance on ${machine} versus number of sites"
        select:
            type: hemelb
        dependent:
            - total
        independent:
            - sites
    performance_versus_cores:
        name: "Performance on ${machine} versus number of sites"
        select:
            type: hemelb
        dependent:
            - total
        independent:
            - cores
            
reports:
  performance_on_planck:
    name: "Performance report for Planck"
    defaults:
      select:
        machine: planck
      curves:
        - build_number
    graphs:
      performance_versus_cores:
        curves:
          - sites
      performance_versus_size:
        curves:
          - cores
  performance_on_oppenheimer:
    name: "Performance report for Oppenheimer"
    defaults:
      select:
        machine: oppenheimer
      curves:
        - build_number
    graphs:
      performance_versus_cores:
        curves:
          - sites
      performance_versus_size:
        curves:
          - cores