# 
# Copyright (C) University College London, 2007-2012, all rights reserved.
# 
# This file is part of HemeLB and is CONFIDENTIAL. You may not work 
# with, install, use, duplicate, modify, redistribute or share this
# file, or any part thereof, other than as allowed by any agreement
# specifically made by you with University College London.
# 

version: 1
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  parsing:
    format: '%(context)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  parsing:
    class: logging.handlers.RotatingFileHandler
    filename: 'parsing.log'
    level: DEBUG
    formatter: parsing
    backupCount: 2
    maxBytes: 65536
loggers:
  parsing:
    level: DEBUG
    handlers: [parsing]
    propagate: no
root:
  level: DEBUG
  handlers: [console]