version: 1
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  parsing:
    format: '%(file)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  parsing:
    class: logging.StreamHandler
    level: DEBUG
    formatter: parsing
    stream: ext://sys.stdout
loggers:
  parsing:
    level: DEBUG
    handlers: [parsing]
    propagate: no
root:
  level: DEBUG
  handlers: [console]